### PR TITLE
feat(swap): show minimum deposit required for min_quantity + fee 

### PR DESCRIPTION
**Pull request by delta1**
Updates swap cli to calculate and show the minimum BTC deposit required to cover the minimum_quantity + fee for a seller #761

### CODE REVIEW

**Comment by binarybaron** [comment]
Thanks a lot again for completing this. It'll definitely improve usability a ton even though it's quite a small change.

The code looks good to me! Can't test it myself right now but I'll give you the benefit of the doubt :)

@lescuer97 Have you had a time take a look yet? Otherwise I'd be fine with merging this!

**Review by binarybaron — APPROVED** [review]
Thanks a lot again for completing this. It'll definitely improve usability a ton even though it's quite a small change.

The code looks good to me! Can't test it myself right now but I'll give you the benefit of the doubt :)

@lescuer97 Have you had a time take a look yet? Otherwise I'd be fine with merging this!

**Comment by delta1** [comment]
Yeah it really does help to see what the minimum required deposit is. I have done a few successful swaps on testnet with this, so I think it is working well.

**Comment by lescuer97** [comment]
LGTM - any of you @binarybaron  or @delta1  ran It on testnet with a full trade?

**Comment by lescuer97** [comment]
> Yeah it really does help to see what the minimum required deposit is. I have done a few successful swaps on testnet with this, so I think it is working well.

disregard, I did not see this comment

**Comment by binarybaron** [comment]
bors try

**Review by lescuer97 — APPROVED** [review]
looks good to me

**Comment by delta1** [comment]
bors merge

**Pull request merged**
