### PR TITLE
Wait for refund if insufficient Monero is locked up

### PR DESCRIPTION
**Pull request by da-kami**
In a scenario where Alice does not lock up sufficient funds Bob should properly transition to refunds. At the moment the CLI just panics. 
I noticed this when Alice accidentally had a different amount set than Bob. In the future this should not happen, because Alice provides the amount for Bob. However, in case Alice is malicious Bob should still transition correctly.

### CODE REVIEW

**Review by thomaseizinger — COMMENTED** [review]
Is this really the whole change? I don't quite understand where `InsufficientFunds` is created and how it panicked before.

**Comment by da-kami** [comment]
> Is this really the whole change? I don't quite understand where `InsufficientFunds` is created and how it panicked before.

Insufficient funds was triggered in a function inside, and we just questionmarked it. But I think the error handling should be in `run_until_internal`, because there we have to take the decision.
So I used a two-fold Result again to be able to go on in case the problem was related to insufficient funds.

**Comment by thomaseizinger** [comment]
> > Is this really the whole change? I don't quite understand where `InsufficientFunds` is created and how it panicked before.
> 
> Insufficient funds was triggered in a function inside, and we just questionmarked it in `run_until_internal`. But I think the error handling should be in `run_until_internal`, because there we have to take the decision.
> So I used a two-fold Result to be able to go on in case the problem was related to insufficient funds.

But you are still questionmarking the error from `watch_for_transfer`?

**Comment by thomaseizinger** [comment]
@da-kami fixed it for you and rebased onto latest master to resolve the conflict.

**Comment by da-kami** [comment]
> @da-kami fixed it for you and rebased onto latest master to resolve the conflict.

The rebase alters `ci.yml` - is that anticipated?

**Pull request merged**
