### PR TITLE
Change monitoring to default wallet

### PR DESCRIPTION
**Pull request by da-kami**
The automated swap backend (asb) requires Monero funds, because Alice is selling Monero.
We use a hardcoded default wallet named asb-wallet. This wallet is opened upon startup.
If the default wallet does not exist it will be created.

Additionally there is a check for the balance - if the balance is zero an address is printed for depositing funds.

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
Nice, thank you!

**Comment by thomaseizinger** [comment]
bors retry

**Comment by da-kami** [comment]
The monero-harness test is acting out again. We had this problem in the past:

```
 thread 'fund_transfer_and_check_tx_key' panicked at 'called `Result::unwrap()` on an `Err` value: missing field `result` at line 8 column 1', monero-harness/tests/wallet.rs:52:10
```

@rishflab do you have any data if it is always the same test that causes this failure?

**Comment by da-kami** [comment]
bors retry

**Comment by da-kami** [comment]
> Build failed:
> 
>     * [docker_tests (happy_path_restart_bob_before_comm)](https://github.com/comit-network/xmr-btc-swap/runs/1948027356)

This failure is weird. The test fails when locking Bitcoin (Bob) because Bob's balance is `0`. The changes of this PR neither touch bitcoin setup nor the test code. It looks like the test setup is not stable enough. I will see if I can reproduce this locally.

**Comment by da-kami** [comment]
> > Build failed:
> > ```
> > * [docker_tests (happy_path_restart_bob_before_comm)](https://github.com/comit-network/xmr-btc-swap/runs/1948027356)
> > ```
> 
> This failure is weird. The test fails when locking Bitcoin (Bob) because Bob's balance is `0`. The changes of this PR neither touch bitcoin setup nor the test code. It looks like the test setup is not stable enough. I will see if I can reproduce this locally.

https://github.com/comit-network/xmr-btc-swap/pull/216

**Comment by thomaseizinger** [comment]
bors retry

**Comment by da-kami** [comment]
> Timed out.

Computer says no.

**Review by rishflab — APPROVED** [review]

**Comment by da-kami** [comment]
Rebased on master manually, let's give this another try 😅

**Pull request merged**
