### PR TITLE
Create github workflow to build swap_cli binary on release

### LINKED ISSUE #222: Automated release
Create GitHub actions for an automated release of the swap CLI.

### PR DESCRIPTION
**Pull request by rishflab**
Fixes #222

### CODE REVIEW

**Review by thomaseizinger — COMMENTED** [review]
I just had a search for existing actions. Not sure why we didn't do this earlier. I found this: https://github.com/marketplace/actions/build-and-upload-rust-binary-to-github-releases#example-workflow-basic-usage-multiple-platforms

That could reduce the complexity of all of this significantly. Shall we us it?

**Comment by thomaseizinger** [comment]
> I just had a search for existing actions. Not sure why we didn't do this earlier. I found this: [github.com/marketplace/actions/build-and-upload-rust-binary-to-github-releases#example-workflow-basic-usage-multiple-platforms](https://github.com/marketplace/actions/build-and-upload-rust-binary-to-github-releases#example-workflow-basic-usage-multiple-platforms)
> 
> That could reduce the complexity of all of this significantly. Shall we us it?

Scratch that, you can't point this action to the URL it should use to upload the archive.

**Comment by da-kami** [comment]
I remember that the `comit-rs` setup handled the Changelog as well - do you think it would be worth starting to track our changes on the CLI in a changelog? I think that could come in handy quite soon.

**Review by da-kami — APPROVED** [review]

**Comment by thomaseizinger** [comment]
> I remember that the `comit-rs` setup handled the Changelog as well - do you think it would be worth starting to track our changes on the CLI in a changelog? I think that could come in handy quite soon.

We didn't do the changelog because we don't have git-flow and we can't push to master directly so we'd have to create another branch and wait for that to merge.

I'd keep this as an MVP for now and see how annoying it gets!

**Pull request merged**
