### PR TITLE
fix(asb): Allow history command to be run while asb is running

### PR DESCRIPTION
**Pull request by binarybaron**

### CODE REVIEW

**Comment by binarybaron** [comment]
@Einliterflasche You can review this when you have time

**Review by delta1 — APPROVED** [review]
LGTM

I think it's worth adding a changelog entry so it will be listed with the next release

**Comment by Einliterflasche** [comment]
I don't know how you feel about this, but I feel we could use something like `enum AccessMod { ReadOnly, ReadWrite }` instead of a `bool`, just to make things clearer. I could go ahead and implement it if you agree in principal but find it boring :)

**Comment by binarybaron** [comment]
> I don't know how you feel about this, but I feel we could use something like `enum AccessMode { ReadOnly, ReadWrite }` instead of a `bool`, just to make things clearer. I could go ahead and implement it if you agree in principal but find it boring :)

Sounds good!

**Comment by binarybaron** [comment]
Feel free to open a new PR based on my branch

**Comment by binarybaron** [comment]
superseded by https://github.com/comit-network/xmr-btc-swap/pull/1722

**Pull request closed without merging**
