### PR TITLE
feat: upgrade to monero 0.18

### LINKED ISSUE #1061: `monero-wallet-rpc` failed to fetch transaction while doing a transaction
Not sure quite what's going on here, but when doing a normal transaction, I'm seeing

```
Waiting for Monero transaction finality txid=xxxxx target_confirmations=10
`monero-wallet-rpc` failed to fetch transaction, may need to be restarted txid=xxxxx
Connected to Alice at <address>
`monero-wallet-rpc` failed to fetch transaction, may need to be restarted txid=xxxxx
```

And the monero wallet rpc message keeps repeating.

### LINKED ISSUE #1081: upgrade Monero to 0.18 and release before hardfork on 13 August 2022
https://www.getmonero.org/2022/04/20/network-upgrade-july-2022.html

### PR DESCRIPTION
**Pull request by delta1**
Updates the docker images and wallet-rpc downloads to 0.18.0

closes #1081 
fixes #1061

### CODE REVIEW

**Comment by binarybaron** [comment]
LGTM!

**Review by binarybaron — APPROVED** [review]
LGTM!

**Comment by binarybaron** [comment]
Have you though about implementing an auto updater? (Deleting the monero-wallet-rpc if it's not hardfork ready)

Manually updating the binary might be a bit inconvenient for regular users.

**Comment by delta1** [comment]
Yeah, I did want to try get that in with this. At the very least, check the version and alert the user, but preferably also delete the file and then get the new one.

**Comment by delta1** [comment]
bors merge

**Comment by delta1** [comment]
bors cancel

action was stuck on retrieving cache

**Comment by delta1** [comment]
bors merge

**Pull request merged**
