### PR TITLE
Fetching all UTXOs when doing max_giveable

### PR DESCRIPTION
**Pull request by devbordecraft**
This is fixing #662

### CODE REVIEW

**Review by rishflab — APPROVED** [review]

**Review by rishflab — CHANGES_REQUESTED** [review]
Thanks again. I think this is good to go apart from one thing:

It might be worth  adding a note to the changelog as this change will mean that if you start a swap and you have a leftover UTXO from a previous failed swap, your new swap will include both UTXO's in bitcoin TxLock.

**Comment by thomaseizinger** [comment]
> It might be worth adding a note to the changelog as this change will mean that if you start a swap and you have a leftover UTXO from a previous failed swap, your new swap will include both UTXO's in bitcoin TxLock.

Does that matter much though? We can include it as a `Fixed` as well because I would actually consider it a bug that we weren't doing that currently :)

**Comment by rishflab** [comment]
> > It might be worth adding a note to the changelog as this change will mean that if you start a swap and you have a leftover UTXO from a previous failed swap, your new swap will include both UTXO's in bitcoin TxLock.
> 
> Does that matter much though? We can include it as a `Fixed` as well because I would actually consider it a bug that we weren't doing that currently :)

My memory of the the user interaction is a bit foggy but as far as I remember Bob is prompted to deposit BTC to swap-cli wallet and is under the impression that the amount he deposits is the amount that is swaped. This PR would mean bob's swap more than what he would expect to swap?

**Comment by thomaseizinger** [comment]
> > > It might be worth adding a note to the changelog as this change will mean that if you start a swap and you have a leftover UTXO from a previous failed swap, your new swap will include both UTXO's in bitcoin TxLock.
> > 
> > Does that matter much though? We can include it as a `Fixed` as well because I would actually consider it a bug that we weren't doing that currently :)
> 
> My memory of the the user interaction is a bit foggy but as far as I remember Bob is prompted to deposit BTC to swap-cli wallet and is under the impression that the amount he deposits is the amount that is swaped. This PR would mean bob's swap more than what he would expect to swap?

If there is money left in the wallet, we don't prompt at all. Even dodgier but that is the current behaviour 😅

**Comment by rishflab** [comment]
@devbordecraft recreated this here #717 preserving your commits. just wanted to get it into release 0.8.2 asap and couldn't wait for further back and forth over merge conflicts/ minor changes.

**Pull request closed without merging**
