### PR TITLE
Disable `backoff`s `max_elapsed_time` functionality

### LINKED ISSUE #303: Kraken websocket stream closes connection unexpectedly
This causes the rate-module to report a permanent error, which results in quote failing quote requests from the CLI.

Error log from the ASB:

```
Mar 10 14:57:52 raspberrypi cargo[5639]: Mar 10 14:57:52.136 DEBUG swap{id=8108a02b-377e-48f6-a4d6-90880887e94c}: swap::bitcoin::wallet: confirmations: BlockHeight(1) txid=eca50dfa7e53f1d65c759136ea67c0895a05afe9778a023cc344ffe705a7e5f4
Mar 10 14:57:52 raspberrypi cargo[5639]: Mar 10 14:57:52.138  INFO swap{id=8108a02b-377e-48f6-a4d6-90880887e94c}: swap::protocol::alice::swap: Current state: btc is redeemed
Mar 10 15:33:39 raspberrypi cargo[5639]: Mar 10 15:33:39.326  WARN swap::kraken: Rate updates incurred an unrecoverable error: Failed to read message from websocket stream: IO error: Connection reset by peer (os error 104)
Mar 10 23:45:56 raspberrypi cargo[5639]: Mar 10 23:45:56.680 DEBUG swap::protocol::alice::event_loop: Connection Established with 12D3KooWRvzPVmsH6Y7hLaMFjQU39LZqtWAhd8zNQDsz3TqNfev9
Mar 10 23:45:56 raspberrypi cargo[5639]: Mar 10 23:45:56.685  WARN swap::protocol::alice::event_loop: failed to make quote: Failed to get latest rate: Permanently failed to retrieve rate from Kraken peer=12D3KooWRvzPVmsH6Y7hLaMFjQU39LZqtWAhd8zNQDsz3TqNfev9
Mar 10 23:45:56 raspberrypi cargo[5639]: Mar 10 23:45:56.686 ERROR swap::protocol::alice::event_loop: Communication error: quote protocol with peer 12D3KooWRvzPVmsH6Y7hLaMFjQU39LZqtWAhd8zNQDsz3TqNfev9 failed due to ResponseOmission
```

The Kraken documentation states, that unexpected closing of connections can happen due to the same IP address being used over longer period of time which might cause Cloudflare to close the connection: 

https://support.kraken.com/hc/en-us/articles/360044504011-WebSocket-API-unexpected-disconnections-from-market-data-feeds

### PR DESCRIPTION
**Pull request by thomaseizinger**
This config setting makes backoff stop retrying if we didn't get an
error within this timeframe.
For us, this results in backoff not actually doing anything.

The connection to kraken is very long-running. It might be active
for hours without failing. However, the default value for
`max_elapsed_time` is set to 15 minutes. As such, once the connection
fails any time after that, backoff doesn't actually retry the operation
but just gives up.

Fixes #303.

### CODE REVIEW

**Review by da-kami — APPROVED** [review]
Thank you! That explains why we never ran into a retry. I should have dug into `backoff` more thoroughly :)

**Comment by thomaseizinger** [comment]
> Thank you! That explains why we never ran into a retry. I should have dug into `backoff` more thoroughly :)

I was also very surprised by this behaviour and I am considering opening a discussion issue on backoff to remove it or at least change the default. It is not intuitive IMO.

**Review by rishflab — APPROVED** [review]

**Comment by thomaseizinger** [comment]
Opened a discussion issue on `backoff` here: https://github.com/ihrwein/backoff/issues/39

**Pull request merged**
