### PR TITLE
Use rfc3339 date time when logging

### PR DESCRIPTION
**Pull request by rishflab**
Chrono feature is deprecated in tracing-subscriber 0.3.3

Closes #838

### CODE REVIEW

**Review by thomaseizinger — APPROVED** [review]
Nice, needs a rebase though.

**Review by thomaseizinger — APPROVED** [review]

**Comment by da-kami** [comment]
I'll trigger another release after this one goes in

**Comment by da-kami** [comment]
bors retry

**Comment by da-kami** [comment]
bors retry

**Pull request merged**
