### PR TITLE
Re-configure rustfmt to organize imports differently

### PR DESCRIPTION
**Pull request by thomaseizinger**
Initially, I only set out to do a follow-up PR for https://github.com/comit-network/xmr-btc-swap/commit/e3a73d105b2b1482cdac3e21d1d37eb92f6499b5 but stumbled over this rustfmt setting that I wanted to try out for a while already.

Enjoy! I already like it because imports take up less space and reduces the chances of merge conflicts.

### CODE REVIEW

**Review by da-kami — APPROVED** [review]
I like it, I find it more readable and concise than `Crate`.

**Review by rishflab — APPROVED** [review]
I find the nested imports more readable but I guess fewer merge conflicts is nice.

**Comment by thomaseizinger** [comment]
> I find the nested imports more readable but I guess fewer merge conflicts is nice.

Yeah I agree. I liked the visual grouping as well because it is less redundant. Let's see how it goes :)

**Pull request merged**
