### PR TITLE
Don't spam on transaction status change

### PR DESCRIPTION
**Pull request by thomaseizinger**

### CODE REVIEW

**Review by da-kami — APPROVED** [review]

**Review by rishflab — APPROVED** [review]

**Comment by thomaseizinger** [comment]
bors r-

This one is stacked on top of the other one.

**Comment by da-kami** [comment]
> bors r-
> 
> This one is stacked on top of the other one.

Oh sorry, I did not notice that. It is based on `master` ...?

**Comment by da-kami** [comment]
bors retry

**Pull request merged**
