### PR TITLE
Release version 0.12.0

### PR DESCRIPTION
**Pull request by comit-botty-mc-botface**
Hi @binarybaron!

This PR was created in response to a manual trigger of the release workflow here: https://github.com/comit-network/xmr-btc-swap/actions/runs/3795515513.
I've updated the changelog and bumped the versions in the manifest files in this commit: 40f335f442bcf1c6c85a07574f055f6e9cd92ef9.

Merging this PR will create a GitHub release and upload any assets that are created as part of the release build.

### CODE REVIEW

**Comment by binarybaron** [comment]
@delta1 @lescuer97 Any objections? We should release `0.12.0` as soon as possible to make master compatible with the latest stable release again.

**Comment by delta1** [comment]
No objection but I think #1195 could also go in?

**Comment by binarybaron** [comment]
> No objection but I think #1195 could also go in?

Agreed. Left one comment on the PR

https://github.com/comit-network/xmr-btc-swap/pull/1195#pullrequestreview-1231830250

**Comment by lescuer97** [comment]
I can't see anything writen up  in the changelog.

**Comment by binarybaron** [comment]
> I can't see anything writen up in the changelog.

I'll add a changelog entry

**Comment by binarybaron** [comment]
I'll open a new PR. Not sure if the bot is able to rebase

**Pull request closed without merging**
