### PR TITLE
Refresh monero monitoring wallet at startup to ensure daemon is is av…

### PR DESCRIPTION
**Pull request by binarybaron**
…ailable

### CODE REVIEW

**Review by delta1 — APPROVED** [review]
bors r+

**Comment by binarybaron** [comment]
We have to revert this. I don't know if this takes forever if we have a lots of blocks to scan (we haven't used the CLI in a while) and I think we can make this more efficient as the wallet doesn't contain any transactions (99% sure) and is only used to watch the tx transfer proof

**Comment by delta1** [comment]
bors retry

**Comment by delta1** [comment]
bors retry

**Pull request merged**
