### PR TITLE
ASB max sell amount

### PR DESCRIPTION
**Pull request by da-kami**

### CODE REVIEW

**Comment by rishflab** [comment]
Shouldn't max sell amount NOT have a default?  This is something that should be explicitly specified or the program should abort.

**Review by rishflab — CHANGES_REQUESTED** [review]
Shouldn't max sell amount NOT have a default? This is something that should be explicitly specified or the program should abort.

**Comment by da-kami** [comment]
> Shouldn't max sell amount NOT have a default? This is something that should be explicitly specified or the program should abort.

The default was added because at the moment the asb is just a demo application and should always have a limit. It just makes it easier to run the asb without having to alter the setup on the raspberry - and the default does not do any harm.

**Comment by da-kami** [comment]
@thomaseizinger what's your opinion on this default?

**Review by thomaseizinger — APPROVED** [review]
I am fine with a default value as it makes it easier to run for us.

**Pull request merged**
