### PR TITLE
Fix logging and retrying of Monero transaction watching

### PR DESCRIPTION
**Pull request by thomaseizinger**
Hopefully, this should also reduce the load because I am not asking the node every second.

Related: https://github.com/comit-network/xmr-btc-swap/issues/202

### CODE REVIEW

**Review by da-kami — APPROVED** [review]
Thank you! I love the tests :)
I like the `while` loop representing the main condition, that really adds to understandability.

I'm fine with not using `backoff` for the RPC call here as described in comment:

```
// treating every error as transient and retrying
 // is obviously wrong but the jsonrpc client is
// too primitive to differentiate between all the
// cases
```

Note: I added a patch on top of your work, that does not pass the full execution parameters to the monero wallet. I think that the wallet should only know what it cares about. Feel free to squash / drop it :)

**Comment by thomaseizinger** [comment]
It seems you fixed the clippy problems in the follow-up commit. I'll quickly fix that up!

**Comment by da-kami** [comment]
> It seems you fixed the clippy problems in the follow-up commit. I'll quickly fix that up!

Naa, I amended that first :)

**Pull request merged**
