### PR TITLE
Release version 0.11.0

### PR DESCRIPTION
**Pull request by comit-botty-mc-botface**
Hi @binarybaron!

This PR was created in response to a manual trigger of the release workflow here: https://github.com/comit-network/xmr-btc-swap/actions/runs/2196598116.
I've updated the changelog and bumped the versions in the manifest files in this commit: bf6ec141b0fcdedecec24ff74f9b252a03a8133b.

Merging this PR will create a GitHub release and upload any assets that are created as part of the release build.

### CODE REVIEW

**Comment by binarybaron** [comment]
Any objections to merging this? @delta1  @lescuer97

**Comment by lescuer97** [comment]
> Any objections to merging this? @delta1 @lescuer97

I want to do some manual testing first but after that no problem

**Comment by lescuer97** [comment]
also we could merge the stabilization of libp2p, what do you guys thing? @binarybaron @delta1

**Comment by delta1** [comment]
I’d be happy to, I also think a manual test would be good or have you already done so @binarybaron ? 

@lescuer97 I will review your PR today have you tested it again?

**Comment by lescuer97** [comment]
> I’d be happy to, I also think a manual test would be good or have you already done so @binarybaron ?
> 
> @lescuer97 I will review your PR today have you tested it again?

I was fixing some conflicts that came out with the pull request when i merged it with the Identify pull request. I will be testing later this afternoon

**Comment by delta1** [comment]
Closing this for a few more features and fixes to get in, then will do a new release

**Pull request closed without merging**
