### PR TITLE
Upgrade to latest bdk to fix occasional `InsufficientFunds` error

### LINKED ISSUE #546: We sometimes hit `InsufficientFunds` when funding Bitcoin LockTx
I think this happens because we use random keys to predict the weight of `TxLock`. Instead, we should probably hardocde a meaningful weight of `TxLock` and always use that when calculating [`max_giveable`](https://github.com/comit-network/xmr-btc-swap/blob/d5d0dda6e73c76911edcae513a0333ca11a35330/swap/src/bin/swap.rs#L102).

### PR DESCRIPTION
**Pull request by thomaseizinger**
Fixes #546.
Please review patch-by-patch.

### CODE REVIEW

**Comment by thomaseizinger** [comment]
bors retry

**Review by da-kami — COMMENTED** [review]
Thanks for adding the proptests to reproduce the error - and then fixing it by upgrading. 

The test that fails upon bors trying to merge is `can_override_change_address` - I don't think that the specific changes to the test should cause any problem - I think the test failure is related to the changes added in the last commit. (Cannot pinpoint the exact problem without debugging though.)

Do I understand this correctly, that the last commit is just a refactoring on top of the fix? If so I would suggest to drop the last commit and potentially introduce these changes in a follow up.

**Comment by thomaseizinger** [comment]
> Thanks for adding the proptests to reproduce the error - and then fixing it by upgrading.
> 
> The test that fails upon bors trying to merge is `can_override_change_address` - I don't think that the specific changes to the test should cause any problem - I think the test failure is related to the changes added in the last commit. (Cannot pinpoint the exact problem without debugging though.)
> 
> Do I understand this correctly, that the last commit is just a refactoring on top of the fix? If so I would suggest to drop the last commit and potentially introduce these changes in a follow up.

Yeah that is what I am planning on doing :)
Thought it would be nice to clean this up a bit but seems like I've made some mistake so I am not gonna bother with that and just drop it!

**Review by da-kami — APPROVED** [review]

**Pull request merged**
