### PR TITLE
Reorganise modules

### PR DESCRIPTION
**Pull request by rishflab**
Our previous structure did not make sense. We had a state.rs which contained the
storage models at the top level. The actual protocol state was a level lower in
swap::alice and swap::bob. We had protocol code (negotiate.rs/steps.rs) in the
same module as our stateless network code. Created 3 modules for protocol,
network and storage and put the files where they should belong.

### CODE REVIEW

**Comment by da-kami** [comment]
I understand the changes and don't really have a problem with them, but could you maybe describe the motivation for this a bit more? Why do we need this?

**Comment by rishflab** [comment]
> I understand the changes and don't really have a problem with them, but could you maybe describe the motivation for this a bit more? Why do we need this?

Our previous structure did not make sense. We had a state.rs which contained the storage models at the top level. The actual protocol state was a level lower in swap::alice and swap::bob. We had protocol code in the same module as our stateless network code. I created 3 modules for protocol, network and storage and put the files where the should belong.

Will add this explanation to the PR description/commit.

**Review by D4nte — CHANGES_REQUESTED** [review]
Can we avoid re-organisation when we are sprinting towards an end goal? (mainnet).

**Comment by rishflab** [comment]
Closing this as it is too tricky to rebase it. Easier to remake the PR.

**Pull request closed without merging**
