### PR TITLE
Add support for arm architecture to Swap CLI

### PR DESCRIPTION
**Pull request by bonomat**
Tested locally on my RPI4

### CODE REVIEW

**Comment by bonomat** [comment]
@thomaseizinger : can you try the cli on you linux (non-arm) machine please. 

We don't know if we broke by accident linux support.

**Comment by thomaseizinger** [comment]
> @thomaseizinger : can you try the cli on you linux (non-arm) machine please.
> 
> We don't know if we broke by accident linux support.

Works until waiting for funding! Do you want me to test further or is that enough?

**Comment by bonomat** [comment]
> > @thomaseizinger : can you try the cli on you linux (non-arm) machine please.
> > We don't know if we broke by accident linux support.
> 
> Works until waiting for funding! Do you want me to test further or is that enough?

thank you. As long as it successfully downloaded the monero-wallet-rpc binary and was able to started it than all good :)

**Review by da-kami — APPROVED** [review]

**Pull request merged**
