### PR TITLE
Release version 0.12.0

### PR DESCRIPTION
**Pull request by comit-botty-mc-botface**
Hi @binarybaron!

This PR was created in response to a manual trigger of the release workflow here: https://github.com/comit-network/xmr-btc-swap/actions/runs/3810048887.
I've updated the changelog and bumped the versions in the manifest files in this commit: d7104c6976e2ca749ec0b63b5ae9ed8b417d04f1.

Merging this PR will create a GitHub release and upload any assets that are created as part of the release build.

### CODE REVIEW

**Comment by binarybaron** [comment]
bors t+

**Comment by delta1** [comment]
@binarybaron what about #1184 ? Still an issue unless everyone is expected to upgrade?

**Comment by binarybaron** [comment]
I believed the consensus was to introduce a breaking change and deal with the consequences of forcing everyone to upgrade.

**Pull request merged**
