### PR TITLE
Monero wallet refresh fix redux 

### PR DESCRIPTION
**Pull request by delta1**
recreating #1487

### CODE REVIEW

**Comment by delta1** [comment]
@binarybaron good news, for whatever reason CI seems to pass on this now. Ran it twice and it's all green.

**Comment by binarybaron** [comment]
This PR is empty. The changes from the original PR were not merged into master.

**Comment by delta1** [comment]
oh, derp. sorry.

**Comment by delta1** [comment]
recreated your diff in #1596

**Pull request merged**
